/**
 * 想定質問管理フック
 *
 * Q&Aペアのローカル編集状態を管理し、IPCを通じてクラウドと同期。
 * useDocumentsと同じパターンに従う。
 */

import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import { createLogger } from '../utils/logger'

const log = createLogger('useInterviewQuestions')

// InterviewQuestion, QuestionInput はグローバル型（env.d.ts経由）

export interface LocalQuestion {
  id?: string
  localId: string
  question: string
  answer: string
  isAutoGenerated: boolean
}

export interface UseInterviewQuestionsReturn {
  questions: LocalQuestion[]
  isLoading: boolean
  isSaving: boolean
  error: string | null
  hasUnsavedChanges: boolean

  updateQuestion: (index: number, field: 'question' | 'answer', value: string) => void
  addQuestion: () => void
  removeQuestion: (index: number) => void
  saveQuestions: () => Promise<void>
  refreshQuestions: () => Promise<void>
}

export const MAX_QUESTIONS = 20

export function useInterviewQuestions(): UseInterviewQuestionsReturn {
  const [questions, setQuestions] = useState<LocalQuestion[]>([])
  const [savedSnapshot, setSavedSnapshot] = useState<string>('')
  const [isLoading, setIsLoading] = useState(true)
  const [isSaving, setIsSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const mountedRef = useRef(true)
  const questionsRef = useRef(questions)
  questionsRef.current = questions

  const hasUnsavedChanges = useMemo(
    () => JSON.stringify(questions) !== savedSnapshot,
    [questions, savedSnapshot]
  )

  const loadQuestions = useCallback(async () => {
    try {
      setIsLoading(true)
      setError(null)
      log.debug('Loading questions')

      const result = await window.electron.questions.list()

      if (!mountedRef.current) return

      if (result.success && result.questions) {
        const loaded = result.questions.map((q: InterviewQuestion) => ({
          id: q.id,
          localId: q.id,
          question: q.question,
          answer: q.answer,
          isAutoGenerated: q.isAutoGenerated,
        }))
        setQuestions(loaded)
        setSavedSnapshot(JSON.stringify(loaded))
        log.info('Questions loaded', { count: loaded.length })
      } else if (result.error) {
        setError(result.error)
        log.error('Failed to load questions', { error: result.error })
      }
    } catch (err) {
      if (mountedRef.current) {
        setError(String(err))
        log.error('Questions load error', { error: String(err) })
      }
    } finally {
      if (mountedRef.current) {
        setIsLoading(false)
      }
    }
  }, [])

  useEffect(() => {
    mountedRef.current = true
    loadQuestions()
    return () => {
      mountedRef.current = false
    }
  }, [loadQuestions])

  const updateQuestion = useCallback(
    (index: number, field: 'question' | 'answer', value: string) => {
      setQuestions((prev) =>
        prev.map((q, i) => (i === index ? { ...q, [field]: value } : q))
      )
    },
    []
  )

  const addQuestion = useCallback(() => {
    setQuestions((prev) => {
      if (prev.length >= MAX_QUESTIONS) return prev
      return [
        ...prev,
        { localId: crypto.randomUUID(), question: '', answer: '', isAutoGenerated: false },
      ]
    })
  }, [])

  const removeQuestion = useCallback((index: number) => {
    setQuestions((prev) => prev.filter((_, i) => i !== index))
  }, [])

  // questionsRefを使って最新の状態を参照（stale closure防止）
  const saveQuestions = useCallback(async () => {
    try {
      setIsSaving(true)
      setError(null)
      log.info('Saving questions')

      const currentQuestions = questionsRef.current
      const inputs: QuestionInput[] = currentQuestions
        .filter((q) => q.question.trim().length > 0)
        .map((q, i) => ({
          id: q.id,
          question: q.question.trim(),
          answer: q.answer.trim(),
          sortOrder: i,
        }))

      const result = await window.electron.questions.save(inputs)

      if (!mountedRef.current) return

      if (result.success && result.questions) {
        const saved = result.questions.map((q: InterviewQuestion) => ({
          id: q.id,
          localId: q.id,
          question: q.question,
          answer: q.answer,
          isAutoGenerated: q.isAutoGenerated,
        }))
        setQuestions(saved)
        setSavedSnapshot(JSON.stringify(saved))
        log.info('Questions saved', { count: saved.length })
      } else if (result.error) {
        setError(result.error)
        log.error('Save failed', { error: result.error })
      }
    } catch (err) {
      if (mountedRef.current) {
        setError(String(err))
        log.error('Save error', { error: String(err) })
      }
    } finally {
      if (mountedRef.current) {
        setIsSaving(false)
      }
    }
  }, [])

  const refreshQuestions = useCallback(async () => {
    await loadQuestions()
  }, [loadQuestions])

  return {
    questions,
    isLoading,
    isSaving,
    error,
    hasUnsavedChanges,
    updateQuestion,
    addQuestion,
    removeQuestion,
    saveQuestions,
    refreshQuestions,
  }
}
