/// <reference types="vite/client" />

interface TranscriptResult {
  text: string
  isFinal: boolean
  confidence: number
  timestamp: number
  source?: 'mic' | 'system'
}

interface AIResponse {
  answer: string
  suggestions: string[]
  confidence: number
}

type DocType = 'resume' | 'job_posting' | 'expected_qa'

interface InterviewQuestion {
  id: string
  question: string
  answer: string
  sortOrder: number
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

interface QuestionInput {
  id?: string
  question: string
  answer: string
  sortOrder: number
}

interface GeneratedQuestion {
  question: string
  answer: string
}

interface InterviewProfile {
  fullName: string
  nameReading?: string
  currentCompany?: string
  currentPosition?: string
  previousCompanies?: string[]
  targetCompany?: string
  targetPosition?: string
  technologies?: string[]
  certifications?: string[]
  education?: string
  yearsOfExperience?: number
  additionalNotes?: string
}

type AudioSource = 'mic' | 'system' | 'both'

interface DocumentInfo {
  id: string
  name: string
  type: DocType
  uploadedAt: number
  chunkCount: number
}

interface AppSettings {
  theme: 'dark' | 'light'
  autoGenerateAI: boolean
  audioSource: AudioSource
  aiModel: 'gpt-5-nano' | 'gpt-5-mini' | 'gpt-5' | 'gpt-4o'
  aiTemperature: number
  aiMaxTokens: number
  contextMinSimilarity: number
  contextTopK: number
  lastUpdated: number
  version: string
}

type SubscriptionTier = 'free' | 'pro' | 'max'
type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'trialing'

interface User {
  id: string
  email: string
  name: string | null
  picture: string | null
  subscriptionTier: SubscriptionTier
  subscriptionStatus: SubscriptionStatus
  subscriptionPeriodEnd: string | null
  usage: {
    sttMinutes: number
    aiTokens: number
    storageBytes: number
  }
  interviewProfile: InterviewProfile | null
}

interface UserSettings {
  theme: 'dark' | 'light'
  autoGenerateAI: boolean
  aiModel: string
  aiTemperature: number
  aiMaxTokens: number
  contextMinSimilarity: number
  contextTopK: number
}

interface AuthState {
  isAuthenticated: boolean
  isLoading: boolean
  user: User | null
  settings: UserSettings | null
  error: string | null
}

interface GenerateOptions {
  includeDocumentContext?: boolean
  maxTokens?: number
}

interface Window {
  electron: {
    auth: {
      getState: () => Promise<{ success: boolean; state?: AuthState; error?: string }>
      loginWithGoogle: () => Promise<{ success: boolean; error?: string }>
      validate: () => Promise<{ success: boolean; state?: AuthState; error?: string }>
      logout: () => Promise<{ success: boolean; state?: AuthState; error?: string }>
      getToken: () => Promise<{ success: boolean; token?: string | null; error?: string }>
      onStateChanged: (callback: (state: AuthState) => void) => () => void
    }
    stt: {
      start: () => Promise<{ success: boolean; error?: string }>
      stop: () => Promise<{ success: boolean; error?: string }>
      sendAudio: (audioData: ArrayBuffer, source?: 'mic' | 'system') => void
      status: () => Promise<{ connected: boolean }>
      onTranscript: (callback: (result: TranscriptResult) => void) => void
      removeTranscriptListener: () => void
    }
    ai: {
      init: (apiKey?: string) => Promise<{ success: boolean; error?: string }>
      generate: (
        question: string,
        context?: string,
        options?: GenerateOptions
      ) => Promise<{ success: boolean; response?: AIResponse; error?: string }>
      generateStream: (
        question: string,
        context?: string,
        options?: GenerateOptions
      ) => Promise<{ success: boolean; response?: AIResponse; error?: string }>
      summarize: (
        previousSummary: string,
        interviewer: string,
        candidate: string
      ) => Promise<{ success: boolean; summary?: string; error?: string }>
      prefetchContext: () => Promise<{ success: boolean; context?: string; error?: string }>
      abort: () => Promise<void>
      status: () => Promise<{ initialized: boolean }>
      onChunk: (callback: (chunk: string) => void) => void
      onComplete: (callback: (response: AIResponse) => void) => void
      onError: (callback: (error: string) => void) => void
      removeListeners: () => void
    }
    document: {
      init: () => Promise<{ success: boolean; error?: string }>
      upload: (type: DocType) => Promise<{
        success: boolean
        error?: string
        document?: DocumentInfo & { wordCount: number }
      }>
      list: () => Promise<{ success: boolean; documents: DocumentInfo[] }>
      remove: (id: string) => Promise<{ success: boolean; error?: string }>
    }
    settings: {
      get: () => Promise<{ success: boolean; settings?: AppSettings; error?: string }>
      save: (
        settings: Partial<AppSettings>
      ) => Promise<{ success: boolean; settings?: AppSettings; error?: string }>
      reset: () => Promise<{ success: boolean; settings?: AppSettings; error?: string }>
    }
    audio: {
      setSource: (source: AudioSource) => Promise<{ success: boolean; error?: string }>
      getSource: () => Promise<{ success: boolean; source: AudioSource; error?: string }>
    }
    questions: {
      list: () => Promise<{ success: boolean; questions?: InterviewQuestion[]; error?: string }>
      save: (
        questions: QuestionInput[]
      ) => Promise<{ success: boolean; questions?: InterviewQuestion[]; error?: string }>
      delete: (id: string) => Promise<{ success: boolean; error?: string }>
      generate: (
        count?: number
      ) => Promise<{ success: boolean; questions?: GeneratedQuestion[]; error?: string }>
    }
    window: {
      minimize: () => Promise<void>
      maximize: () => Promise<void>
      close: () => Promise<void>
      isMaximized: () => Promise<boolean>
    }
    profile: {
      get: () => Promise<{ success: boolean; profile?: InterviewProfile | null; error?: string }>
      save: (
        profile: InterviewProfile
      ) => Promise<{ success: boolean; interviewProfile?: InterviewProfile; error?: string }>
    }
    subscription: {
      getPlans: () => Promise<{ success: boolean; data?: unknown; error?: string }>
      checkout: (priceId: string) => Promise<{ success: boolean; error?: string }>
      portal: () => Promise<{ success: boolean; error?: string }>
      refresh: () => Promise<{ success: boolean; data?: unknown; error?: string }>
    }
    send: (channel: string, data: unknown) => void
    on: (channel: string, callback: (...args: unknown[]) => void) => void
    invoke: (channel: string, data?: unknown) => Promise<unknown>
    removeAllListeners: (channel: string) => void
  }
}
