import { describe, it, expect, vi, beforeEach } from 'vitest'
import { Hono } from 'hono'
import type { Env, Variables } from '../../src/types'
import { generateJWT } from '../../src/lib/auth'

const TEST_JWT_SECRET = 'test-jwt-secret-key-for-testing-purposes-only'
const TEST_USER_ID = 'user-123'

// --- Mock setup ---

const mockChain: Record<string, ReturnType<typeof vi.fn>> = {}
const chainMethods = ['select', 'insert', 'update', 'delete', 'eq', 'single', 'is', 'order', 'in', 'limit']
for (const m of chainMethods) {
  mockChain[m] = vi.fn().mockReturnValue(mockChain)
}
const mockRpc = vi.fn()

vi.mock('../../src/lib/supabase', () => ({
  createSupabaseAdmin: () => ({
    from: vi.fn().mockReturnValue(mockChain),
    rpc: mockRpc,
  }),
}))

vi.mock('../../src/lib/usage', () => ({
  checkUsageLimit: vi.fn(),
  checkAndReserveUsage: vi.fn(),
  adjustReservedUsage: vi.fn(),
  recordUsage: vi.fn(),
}))

vi.mock('../../src/lib/openai', () => ({
  generateEmbeddings: vi.fn().mockResolvedValue([[0.1, 0.2], [0.3, 0.4]]),
}))

vi.mock('../../src/lib/profile', () => ({
  formatProfileContext: vi.fn().mockReturnValue(''),
}))

vi.mock('openai', () => {
  return {
    default: vi.fn().mockImplementation(() => ({
      chat: {
        completions: {
          create: vi.fn(),
        },
      },
    })),
  }
})

import questionsRoutes from '../../src/routes/questions'
import { checkUsageLimit, checkAndReserveUsage } from '../../src/lib/usage'

const TEST_ENV = {
  JWT_SECRET: TEST_JWT_SECRET,
  SUPABASE_URL: 'https://test.supabase.co',
  SUPABASE_SERVICE_ROLE_KEY: 'test-key',
  OPENAI_API_KEY: 'test-openai-key',
} as Env

async function createAuthHeaders(): Promise<Record<string, string>> {
  const token = await generateJWT(
    { sub: TEST_USER_ID, email: 'test@example.com', name: 'Test', picture: '' },
    TEST_JWT_SECRET
  )
  return { Authorization: `Bearer ${token}` }
}

function createApp() {
  const app = new Hono<{ Bindings: Env; Variables: Variables }>()
  app.route('/api/questions', questionsRoutes)
  return app
}

function resetMocks() {
  vi.clearAllMocks()
  for (const m of chainMethods) {
    mockChain[m] = vi.fn().mockReturnValue(mockChain)
  }
}

// --- Tests ---

describe('GET /api/questions', () => {
  beforeEach(resetMocks)

  it('returns 401 without auth', async () => {
    const app = createApp()
    const res = await app.request('/api/questions', {}, TEST_ENV)
    expect(res.status).toBe(401)
  })

  it('returns questions list', async () => {
    const questions = [
      {
        id: 'q-1',
        question: '自己紹介をお願いします',
        answer: '田中太郎です',
        sort_order: 0,
        is_auto_generated: false,
        created_at: '2026-01-01T00:00:00Z',
        updated_at: '2026-01-01T00:00:00Z',
      },
    ]

    mockChain.limit = vi.fn().mockResolvedValue({ data: questions, error: null })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', { headers }, TEST_ENV)

    expect(res.status).toBe(200)
    const body = await res.json()
    expect(body.success).toBe(true)
    expect(body.questions).toHaveLength(1)
    expect(body.questions[0].id).toBe('q-1')
    expect(body.questions[0].sortOrder).toBe(0)
    expect(body.questions[0].isAutoGenerated).toBe(false)
  })

  it('returns 500 on database error', async () => {
    mockChain.limit = vi.fn().mockResolvedValue({ data: null, error: { message: 'DB error' } })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', { headers }, TEST_ENV)

    expect(res.status).toBe(500)
    const body = await res.json()
    expect(body.success).toBe(false)
  })
})

describe('POST /api/questions', () => {
  beforeEach(resetMocks)

  it('returns 401 without auth', async () => {
    const app = createApp()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ questions: [] }),
    }, TEST_ENV)

    expect(res.status).toBe(401)
  })

  it('returns 400 when questions is not an array', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ questions: 'not-array' }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('array')
  })

  it('returns 400 when question text is missing', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        questions: [{ question: '', answer: 'test' }],
      }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('question')
  })

  it('returns 400 when exceeding max questions', async () => {
    const tooMany = Array.from({ length: 21 }, (_, i) => ({
      question: `Q${i}`,
      answer: `A${i}`,
    }))

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ questions: tooMany }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('20')
  })

  it('returns 400 when question exceeds max length', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        questions: [{ question: 'Q'.repeat(501), answer: 'A' }],
      }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('500')
  })

  it('returns 400 when answer exceeds max length', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        questions: [{ question: 'Q', answer: 'A'.repeat(2001) }],
      }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('2000')
  })

  it('returns 429 when AI token limit is exceeded (with answers)', async () => {
    vi.mocked(checkUsageLimit).mockResolvedValue({
      allowed: false,
      used: 30000,
      limit: 30000,
      remaining: 0,
    })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        questions: [{ question: 'Q1', answer: 'A1', sortOrder: 0 }],
      }),
    }, TEST_ENV)

    expect(res.status).toBe(429)
  })

  it('returns 400 for invalid sortOrder', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        questions: [{ question: 'Q1', answer: 'A1', sortOrder: -1 }],
      }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('sortOrder')
  })
})

describe('DELETE /api/questions/:id', () => {
  beforeEach(resetMocks)

  it('returns 401 without auth', async () => {
    const app = createApp()
    const res = await app.request('/api/questions/some-id', { method: 'DELETE' }, TEST_ENV)
    expect(res.status).toBe(401)
  })

  it('returns 400 for invalid UUID', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions/not-a-uuid', {
      method: 'DELETE',
      headers,
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('Invalid question ID')
  })

  it('returns 404 for non-existent question', async () => {
    const validUUID = '550e8400-e29b-41d4-a716-446655440000'
    mockChain.single = vi.fn().mockResolvedValue({
      data: null,
      error: { message: 'not found' },
    })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request(`/api/questions/${validUUID}`, {
      method: 'DELETE',
      headers,
    }, TEST_ENV)

    expect(res.status).toBe(404)
  })

  it('returns 403 when question belongs to different user', async () => {
    const validUUID = '550e8400-e29b-41d4-a716-446655440000'
    mockChain.single = vi.fn().mockResolvedValue({
      data: { id: validUUID, user_id: 'other-user', chunk_id: null },
      error: null,
    })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request(`/api/questions/${validUUID}`, {
      method: 'DELETE',
      headers,
    }, TEST_ENV)

    expect(res.status).toBe(403)
  })

  it('returns 500 when delete operation fails', async () => {
    const validUUID = '550e8400-e29b-41d4-a716-446655440000'

    mockChain.single = vi.fn().mockResolvedValueOnce({
      data: { id: validUUID, user_id: TEST_USER_ID, chunk_id: null },
      error: null,
    })

    // Delete fails
    let eqCount = 0
    mockChain.eq = vi.fn().mockImplementation(() => {
      eqCount++
      if (eqCount === 4) return Promise.resolve({ error: { message: 'delete failed' } })
      return mockChain
    })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request(`/api/questions/${validUUID}`, {
      method: 'DELETE',
      headers,
    }, TEST_ENV)

    expect(res.status).toBe(500)
  })
})

describe('POST /api/questions/generate', () => {
  beforeEach(resetMocks)

  it('returns 401 without auth', async () => {
    const app = createApp()
    const res = await app.request('/api/questions/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    }, TEST_ENV)

    expect(res.status).toBe(401)
  })

  it('returns 400 for invalid count', async () => {
    // Mock chunks query to resolve
    mockChain.in = vi.fn().mockReturnValue(mockChain)
    mockChain.select = vi.fn().mockReturnValue(mockChain)

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions/generate', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ count: 0 }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('count')
  })

  it('returns 400 for count exceeding max', async () => {
    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions/generate', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ count: 21 }),
    }, TEST_ENV)

    expect(res.status).toBe(400)
  })

  it('returns 400 when no documents uploaded', async () => {
    // Chunks query returns empty
    mockChain.in = vi.fn().mockResolvedValue({ data: [], error: null })

    // Profile query
    mockChain.single = vi.fn().mockResolvedValue({
      data: { interview_profile: null },
      error: null,
    })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions/generate', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    }, TEST_ENV)

    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toContain('アップロード')
  })

  it('returns 429 when AI token limit exceeded', async () => {
    // Chunks query returns data
    mockChain.in = vi.fn().mockResolvedValue({
      data: [{ content: 'resume content', documents: { type: 'resume', name: 'resume.pdf' } }],
      error: null,
    })

    // Profile query
    mockChain.single = vi.fn().mockResolvedValue({
      data: { interview_profile: null },
      error: null,
    })

    vi.mocked(checkAndReserveUsage).mockResolvedValue({
      allowed: false,
      used: 30000,
      limit: 30000,
      remaining: 0,
    })

    const app = createApp()
    const headers = await createAuthHeaders()
    const res = await app.request('/api/questions/generate', {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    }, TEST_ENV)

    expect(res.status).toBe(429)
  })
})
