import { contextBridge, ipcRenderer } from 'electron'

export interface TranscriptResult {
  text: string
  isFinal: boolean
  confidence: number
  timestamp: number
  source?: 'mic' | 'system'
}

export interface AIResponse {
  answer: string
  suggestions: string[]
  confidence: number
}

export type DocumentType = 'resume' | 'job_posting' | 'expected_qa'

export interface InterviewQuestion {
  id: string
  question: string
  answer: string
  sortOrder: number
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export interface QuestionInput {
  id?: string
  question: string
  answer: string
  sortOrder: number
}

export interface GeneratedQuestion {
  question: string
  answer: string
}

export interface DocumentInfo {
  id: string
  name: string
  type: DocumentType
  uploadedAt: number
  chunkCount: number
}

// 音声ソースの種類
export interface InterviewProfile {
  fullName: string
  nameReading?: string
  currentCompany?: string
  currentPosition?: string
  previousCompanies?: string[]
  targetCompany?: string
  targetPosition?: string
  technologies?: string[]
  certifications?: string[]
  education?: string
  yearsOfExperience?: number
  additionalNotes?: string
}

export type AudioSource = 'mic' | 'system' | 'both'

export interface AppSettings {
  deepgramApiKey: string
  openaiApiKey: string
  theme: 'dark' | 'light'
  autoGenerateAI: boolean
  audioSource: AudioSource
  aiModel: 'gpt-5-nano' | 'gpt-5-mini' | 'gpt-5' | 'gpt-4o'
  aiTemperature: number
  aiMaxTokens: number
  contextMinSimilarity: number
  contextTopK: number
  lastUpdated: number
  version: string
}

// 認証関連の型
export type SubscriptionTier = 'free' | 'pro' | 'max'
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'trialing'

export interface User {
  id: string
  email: string
  name: string | null
  picture: string | null
  subscriptionTier: SubscriptionTier
  subscriptionStatus: SubscriptionStatus
  subscriptionPeriodEnd: string | null
  usage: {
    sttMinutes: number
    aiTokens: number
    storageBytes: number
  }
  interviewProfile: InterviewProfile | null
}

export interface UserSettings {
  theme: 'dark' | 'light'
  autoGenerateAI: boolean
  aiModel: string
  aiTemperature: number
  aiMaxTokens: number
  contextMinSimilarity: number
  contextTopK: number
  hasCustomDeepgramKey: boolean
  hasCustomOpenaiKey: boolean
}

export interface AuthState {
  isAuthenticated: boolean
  isLoading: boolean
  user: User | null
  settings: UserSettings | null
  error: string | null
}

// 許可されたIPCチャンネルのホワイトリスト（セキュリティ向上）
const ALLOWED_SEND_CHANNELS = ['stt:audio'] as const
const ALLOWED_INVOKE_CHANNELS = [
  'config:getApiKey',
  'stt:start',
  'stt:stop',
  'stt:status',
  'ai:init',
  'ai:generate',
  'ai:generateStream',
  'ai:abort',
  'ai:status',
  'context:init',
  'document:upload',
  'document:list',
  'document:remove',
  // 想定質問関連
  'questions:list',
  'questions:save',
  'questions:delete',
  'questions:generate',
  'settings:get',
  'settings:save',
  'settings:reset',
  'settings:getEffectiveApiKey',
  // プロフィール関連
  'profile:get',
  'profile:save',
  // 認証関連
  'auth:getState',
  'auth:loginWithGoogle',
  'auth:validate',
  'auth:logout',
  'auth:getToken',
  // 音声キャプチャ関連 (Phase 6.5)
  'audio:setSource',
  'audio:getSource',
  // ウィンドウ操作
  'window:minimize',
  'window:maximize',
  'window:close',
  'window:isMaximized',
  // サブスクリプション関連 (Phase 7)
  'subscription:getPlans',
  'subscription:checkout',
  'subscription:portal',
  'subscription:refresh',
] as const
const ALLOWED_ON_CHANNELS = [
  'stt:transcript',
  'ai:chunk',
  'ai:complete',
  'ai:error',
  // 認証関連
  'auth:stateChanged',
] as const

type AllowedSendChannel = (typeof ALLOWED_SEND_CHANNELS)[number]
type AllowedInvokeChannel = (typeof ALLOWED_INVOKE_CHANNELS)[number]
type AllowedOnChannel = (typeof ALLOWED_ON_CHANNELS)[number]

let audioSendCount = 0

const electronAPI = {
  // 認証API
  auth: {
    getState: (): Promise<{ success: boolean; state?: AuthState; error?: string }> =>
      ipcRenderer.invoke('auth:getState'),
    loginWithGoogle: (): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('auth:loginWithGoogle'),
    validate: (): Promise<{ success: boolean; state?: AuthState; error?: string }> =>
      ipcRenderer.invoke('auth:validate'),
    logout: (): Promise<{ success: boolean; state?: AuthState; error?: string }> =>
      ipcRenderer.invoke('auth:logout'),
    getToken: (): Promise<{ success: boolean; token?: string | null; error?: string }> =>
      ipcRenderer.invoke('auth:getToken'),
    onStateChanged: (callback: (state: AuthState) => void): (() => void) => {
      const handler = (_event: unknown, state: AuthState) => callback(state)
      ipcRenderer.on('auth:stateChanged', handler)
      // 個別リスナーの解除関数を返す（removeAllListenersは他のインスタンスのリスナーも消すため使わない）
      return () => ipcRenderer.removeListener('auth:stateChanged', handler)
    },
  },

  // 設定API
  config: {
    getApiKey: (keyName: string): Promise<string | null> =>
      ipcRenderer.invoke('config:getApiKey', keyName),
  },

  // STT (音声認識) API
  stt: {
    // APIキーはMain processで環境変数から直接取得（セキュリティ向上）
    start: () => ipcRenderer.invoke('stt:start'),
    stop: () => {
      audioSendCount = 0 // カウンターをリセット
      return ipcRenderer.invoke('stt:stop')
    },
    sendAudio: (audioData: ArrayBuffer, source?: 'mic' | 'system') => {
      // ArrayBufferをUint8Arrayに変換してからIPC送信
      const uint8Array = new Uint8Array(audioData)
      audioSendCount++
      ipcRenderer.send('stt:audio', Array.from(uint8Array), source)
    },
    status: () => ipcRenderer.invoke('stt:status'),
    onTranscript: (callback: (result: TranscriptResult) => void) => {
      ipcRenderer.on('stt:transcript', (_event, result) => callback(result))
    },
    removeTranscriptListener: () => {
      ipcRenderer.removeAllListeners('stt:transcript')
    },
  },

  // AI API
  ai: {
    init: (apiKey?: string) => ipcRenderer.invoke('ai:init', apiKey),
    generate: (question: string, context?: string) =>
      ipcRenderer.invoke('ai:generate', question, context),
    generateStream: (question: string, context?: string) =>
      ipcRenderer.invoke('ai:generateStream', question, context),
    abort: () => ipcRenderer.invoke('ai:abort'),
    status: () => ipcRenderer.invoke('ai:status'),
    onChunk: (callback: (chunk: string) => void) => {
      ipcRenderer.on('ai:chunk', (_event, chunk) => callback(chunk))
    },
    onComplete: (callback: (response: AIResponse) => void) => {
      ipcRenderer.on('ai:complete', (_event, response) => callback(response))
    },
    onError: (callback: (error: string) => void) => {
      ipcRenderer.on('ai:error', (_event, error) => callback(error))
    },
    removeListeners: () => {
      ipcRenderer.removeAllListeners('ai:chunk')
      ipcRenderer.removeAllListeners('ai:complete')
      ipcRenderer.removeAllListeners('ai:error')
    },
  },

  // Document API
  document: {
    init: (): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('context:init'),
    upload: (
      type: DocumentType
    ): Promise<{
      success: boolean
      error?: string
      document?: DocumentInfo & { wordCount: number }
    }> => ipcRenderer.invoke('document:upload', type),
    list: (): Promise<{ success: boolean; documents: DocumentInfo[] }> =>
      ipcRenderer.invoke('document:list'),
    remove: (id: string): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('document:remove', id),
  },

  // Settings API
  settings: {
    get: (): Promise<{ success: boolean; settings?: AppSettings; error?: string }> =>
      ipcRenderer.invoke('settings:get'),
    save: (
      settings: Partial<AppSettings>
    ): Promise<{ success: boolean; settings?: AppSettings; error?: string }> =>
      ipcRenderer.invoke('settings:save', settings),
    reset: (): Promise<{ success: boolean; settings?: AppSettings; error?: string }> =>
      ipcRenderer.invoke('settings:reset'),
    getEffectiveApiKey: (
      keyType: 'deepgram' | 'openai'
    ): Promise<{ success: boolean; key?: string | null }> =>
      ipcRenderer.invoke('settings:getEffectiveApiKey', keyType),
  },

  // Audio API (Phase 6.5: システム音声キャプチャ)
  audio: {
    setSource: (
      source: AudioSource
    ): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('audio:setSource', source),
    getSource: (): Promise<{ success: boolean; source: AudioSource; error?: string }> =>
      ipcRenderer.invoke('audio:getSource'),
  },

  // Questions API (Phase 9: 想定質問)
  questions: {
    list: (): Promise<{ success: boolean; questions?: InterviewQuestion[]; error?: string }> =>
      ipcRenderer.invoke('questions:list'),
    save: (
      questions: QuestionInput[]
    ): Promise<{ success: boolean; questions?: InterviewQuestion[]; error?: string }> =>
      ipcRenderer.invoke('questions:save', questions),
    delete: (id: string): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('questions:delete', id),
    generate: (
      count?: number
    ): Promise<{ success: boolean; questions?: GeneratedQuestion[]; error?: string }> =>
      ipcRenderer.invoke('questions:generate', count),
  },

  // Window API (カスタムタイトルバー)
  window: {
    minimize: (): Promise<void> => ipcRenderer.invoke('window:minimize'),
    maximize: (): Promise<void> => ipcRenderer.invoke('window:maximize'),
    close: (): Promise<void> => ipcRenderer.invoke('window:close'),
    isMaximized: (): Promise<boolean> => ipcRenderer.invoke('window:isMaximized'),
  },

  // Profile API (面接プロフィール)
  profile: {
    get: (): Promise<{ success: boolean; profile?: InterviewProfile | null; error?: string }> =>
      ipcRenderer.invoke('profile:get'),
    save: (
      profile: InterviewProfile
    ): Promise<{ success: boolean; interviewProfile?: InterviewProfile; error?: string }> =>
      ipcRenderer.invoke('profile:save', profile),
  },

  // Subscription API (Phase 7: Stripe 決済)
  subscription: {
    getPlans: (): Promise<{ success: boolean; data?: unknown; error?: string }> =>
      ipcRenderer.invoke('subscription:getPlans'),
    checkout: (priceId: string): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('subscription:checkout', priceId),
    portal: (): Promise<{ success: boolean; error?: string }> =>
      ipcRenderer.invoke('subscription:portal'),
    refresh: (): Promise<{ success: boolean; data?: unknown; error?: string }> =>
      ipcRenderer.invoke('subscription:refresh'),
  },

  // 汎用IPC（ホワイトリスト制限付き - セキュリティ向上）
  send: (channel: string, data: unknown) => {
    if (ALLOWED_SEND_CHANNELS.includes(channel as AllowedSendChannel)) {
      ipcRenderer.send(channel, data)
    }
  },
  on: (channel: string, callback: (...args: unknown[]) => void) => {
    if (ALLOWED_ON_CHANNELS.includes(channel as AllowedOnChannel)) {
      ipcRenderer.on(channel, (_event, ...args) => callback(...args))
    }
  },
  invoke: (channel: string, data?: unknown) => {
    if (ALLOWED_INVOKE_CHANNELS.includes(channel as AllowedInvokeChannel)) {
      return ipcRenderer.invoke(channel, data)
    }
    return Promise.reject(new Error(`Channel "${channel}" is not allowed`))
  },
  removeAllListeners: (channel: string) => {
    if (ALLOWED_ON_CHANNELS.includes(channel as AllowedOnChannel)) {
      ipcRenderer.removeAllListeners(channel)
    }
  },
}

contextBridge.exposeInMainWorld('electron', electronAPI)

export type ElectronAPI = typeof electronAPI
