/**
 * 想定質問パネル
 * 左サイドバーに表示。Q&Aの手動入力。
 * DocumentUploadPanelと同じデザイン言語を使用。
 */

import { useState, useCallback, memo } from 'react'
import {
  useInterviewQuestions,
  MAX_QUESTIONS,
  type LocalQuestion,
} from '../hooks/useInterviewQuestions'
import { Card, CardHeader, Button, Badge, Spinner, ErrorAlert } from './ui'

// アイコンコンポーネント
const PlusIcon = () => (
  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
  </svg>
)

const CloseIcon = () => (
  <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="M6 18L18 6M6 6l12 12"
    />
  </svg>
)

const ChevronIcon = ({ expanded }: { expanded: boolean }) => (
  <svg
    className={`w-4 h-4 text-content-secondary transition-transform ${expanded ? 'rotate-90' : ''}`}
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
  >
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
  </svg>
)

const SaveIcon = () => (
  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
  </svg>
)

// QuestionItem の props 型
interface QuestionItemProps {
  index: number
  question: string
  answer: string
  isAutoGenerated: boolean
  expanded: boolean
  onToggle: (index: number) => void
  onUpdateQuestion: (index: number, field: 'question' | 'answer', value: string) => void
  onRemove: (index: number) => void
}

// React.memo で不要な再レンダリングを防止
// 親から安定したコールバック(useCallback)を受け取り、index を内部で適用
const QuestionItem = memo(function QuestionItem({
  index,
  question,
  answer,
  isAutoGenerated,
  expanded,
  onToggle,
  onUpdateQuestion,
  onRemove,
}: QuestionItemProps) {
  const questionId = `question-${index}`
  const answerId = `answer-${index}`

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      onToggle(index)
    }
  }

  return (
    <div className="bg-surface-secondary rounded-lg group">
      {/* ヘッダー（クリック/キーボードで展開） */}
      <div
        role="button"
        tabIndex={0}
        aria-expanded={expanded}
        className="flex items-center gap-2 p-2.5 cursor-pointer hover:bg-surface-hover transition-colors rounded-lg"
        onClick={() => onToggle(index)}
        onKeyDown={handleKeyDown}
      >
        <ChevronIcon expanded={expanded} />
        <span className="text-xs font-medium text-content-tertiary w-5 shrink-0">
          {index + 1}.
        </span>
        <p className="text-sm text-content truncate flex-1 min-w-0">
          {question || '質問を入力...'}
        </p>
        {isAutoGenerated && (
          <Badge variant="info" size="sm">
            自動
          </Badge>
        )}
        <button
          aria-label={`質問${index + 1}を削除`}
          className="p-1 rounded-md opacity-0 group-hover:opacity-100 hover:bg-error-subtle text-content-tertiary hover:text-error transition-all shrink-0"
          onClick={(e) => {
            e.stopPropagation()
            onRemove(index)
          }}
        >
          <CloseIcon />
        </button>
      </div>

      {/* 展開時：入力フィールド */}
      {expanded && (
        <div className="px-3 pb-3 space-y-2">
          <div>
            <label htmlFor={questionId} className="text-xs text-content-tertiary mb-1 block">
              質問
            </label>
            <input
              id={questionId}
              type="text"
              value={question}
              onChange={(e) => onUpdateQuestion(index, 'question', e.target.value)}
              placeholder="面接で聞かれそうな質問"
              maxLength={500}
              className="w-full px-3 py-2 text-sm bg-surface rounded-md border border-border text-content placeholder:text-content-tertiary focus:outline-none focus:ring-1 focus:ring-accent focus:border-accent transition-colors"
            />
          </div>
          <div>
            <label htmlFor={answerId} className="text-xs text-content-tertiary mb-1 block">
              回答
            </label>
            <textarea
              id={answerId}
              value={answer}
              onChange={(e) => onUpdateQuestion(index, 'answer', e.target.value)}
              placeholder="準備した回答（STAR法を意識）"
              maxLength={2000}
              rows={3}
              className="w-full px-3 py-2 text-sm bg-surface rounded-md border border-border text-content placeholder:text-content-tertiary focus:outline-none focus:ring-1 focus:ring-accent focus:border-accent transition-colors resize-y min-h-[60px]"
            />
          </div>
        </div>
      )}
    </div>
  )
})

// メインコンポーネント
function InterviewQuestionsPanel({ onQuestionsUpdated }: { onQuestionsUpdated?: () => void }) {
  const {
    questions,
    isLoading,
    isSaving,
    error,
    hasUnsavedChanges,
    updateQuestion,
    addQuestion,
    removeQuestion,
    saveQuestions,
  } = useInterviewQuestions()

  const [expandedIndex, setExpandedIndex] = useState<number | null>(null)

  // 安定した参照のコールバック（QuestionItemのmemo化を有効にする）
  const handleToggle = useCallback((index: number) => {
    setExpandedIndex((prev) => (prev === index ? null : index))
  }, [])

  const handleRemove = useCallback(
    (index: number) => {
      removeQuestion(index)
      // 削除された項目より上のexpandedIndexを調整
      setExpandedIndex((prev) => {
        if (prev === null) return null
        if (prev === index) return null
        if (prev > index) return prev - 1
        return prev
      })
    },
    [removeQuestion]
  )

  if (isLoading) {
    return (
      <Card variant="default" padding="md">
        <div className="flex items-center justify-center gap-3 py-4">
          <Spinner size="sm" className="text-accent" />
          <span className="text-sm text-content-secondary">読み込み中...</span>
        </div>
      </Card>
    )
  }

  return (
    <Card variant="default" padding="none">
      <div className="p-4 border-b border-border">
        <CardHeader
          title="想定質問"
          subtitle="面接準備"
          action={
            <Badge variant="info" size="sm">
              Q&A
            </Badge>
          }
          className="mb-0"
        />
      </div>

      <div className="p-4 space-y-3">
        {error && <ErrorAlert error={error} />}

        {/* 質問リスト */}
        {questions.length === 0 ? (
          <div className="py-4 text-center">
            <p className="text-xs text-content-tertiary">
              想定質問を追加してください
            </p>
          </div>
        ) : (
          <div className="space-y-1.5 max-h-[400px] overflow-y-auto" role="list">
            {questions.map((q: LocalQuestion, i: number) => (
              <QuestionItem
                key={q.localId}
                index={i}
                question={q.question}
                answer={q.answer}
                isAutoGenerated={q.isAutoGenerated}
                expanded={expandedIndex === i}
                onToggle={handleToggle}
                onUpdateQuestion={updateQuestion}
                onRemove={handleRemove}
              />
            ))}
          </div>
        )}

        {/* 追加ボタン */}
        <Button
          variant="ghost"
          size="sm"
          leftIcon={<PlusIcon />}
          onClick={addQuestion}
          disabled={questions.length >= MAX_QUESTIONS}
          className="w-full"
        >
          質問を追加
        </Button>

        {/* 保存ボタン（未保存変更がある場合のみ） */}
        {hasUnsavedChanges && (
          <Button
            variant="primary"
            size="sm"
            leftIcon={isSaving ? undefined : <SaveIcon />}
            onClick={async () => { await saveQuestions(); onQuestionsUpdated?.() }}
            disabled={isSaving}
            isLoading={isSaving}
            className="w-full"
          >
            {isSaving ? '保存中...' : '保存'}
          </Button>
        )}

        {/* 件数表示 */}
        <p className="text-xs text-content-tertiary text-center">
          {questions.length} / {MAX_QUESTIONS} 件
        </p>
      </div>
    </Card>
  )
}

export default InterviewQuestionsPanel
