export interface InterviewQuestion {
  id: string
  question: string
  answer: string
  sortOrder: number
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export interface QuestionInput {
  id?: string
  question: string
  answer: string
  sortOrder: number
}

export interface GeneratedQuestion {
  question: string
  answer: string
}
