/**
 * 全プロセス（main / preload / renderer）で共有される型定義
 *
 * ソース・オブ・トゥルース: src/renderer/src/env.d.ts から転記。
 * 各プロセスはこのファイルから import して使用する。
 */

// ── STT ─────────────────────────────────────────────

export interface TranscriptResult {
  text: string
  isFinal: boolean
  confidence: number
  timestamp: number
  source?: 'mic' | 'system'
}

// ── AI ──────────────────────────────────────────────

export interface AIResponse {
  answer: string
  suggestions: string[]
  confidence: number
}

/**
 * AI生成オプション（全プロセス共通）
 *
 * NOTE: store は常に false 固定（OpenAIにデータを保存しない）。
 * previousResponseId は廃止済み。会話文脈は直近5ターン + ローリングサマリーで管理する。
 */
export interface GenerateOptions {
  includeDocumentContext?: boolean
  maxTokens?: number
  turnId?: string
  speculativeText?: string
}

/**
 * レンダラー → IPC層への公開インターフェース（GenerateOptionsと同一）
 *
 * 将来レンダラー固有のフィールドが必要になった場合に備えて別名を用意。
 */
export type RendererGenerateOptions = GenerateOptions

// ── ドキュメント ────────────────────────────────────

export type DocType = 'resume' | 'job_posting' | 'expected_qa'

export interface DocumentInfo {
  id: string
  name: string
  type: DocType
  uploadedAt: number
  chunkCount: number
}

// ── 想定質問 ────────────────────────────────────────

export interface InterviewQuestion {
  id: string
  question: string
  answer: string
  sortOrder: number
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export interface QuestionInput {
  id?: string
  question: string
  answer: string
  sortOrder: number
}

// ── プロフィール ────────────────────────────────────

export interface InterviewProfile {
  fullName: string
  nameReading?: string
  currentCompany?: string
  currentPosition?: string
  previousCompanies?: string[]
  targetCompany?: string
  targetPosition?: string
  technologies?: string[]
  certifications?: string[]
  education?: string
  yearsOfExperience?: number
  additionalNotes?: string
}

// ── 認証・サブスクリプション ─────────────────────────

export type SubscriptionTier = 'free' | 'pro' | 'max'
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'trialing'

export interface UserUsage {
  sttMinutes: number
  aiTokens: number
  storageBytes: number
}

export interface User {
  id: string
  email: string
  name: string | null
  picture: string | null
  subscriptionTier: SubscriptionTier
  subscriptionStatus: SubscriptionStatus
  subscriptionPeriodEnd: string | null
  usage: UserUsage
  interviewProfile: InterviewProfile | null
}

export interface AuthState {
  isAuthenticated: boolean
  isLoading: boolean
  user: User | null
  error: string | null
}

// ── 音声 ────────────────────────────────────────────

export type AudioSource = 'mic' | 'system' | 'both'
