/**
 * 想定質問ページ
 * Q&A準備（全画面幅）
 */

import { useCallback, memo } from 'react'
import { useInterviewQuestions } from '../../hooks/useInterviewQuestions'
import { PageHeader } from '../ui/PageHeader'
import { Button, Badge, Spinner, ErrorAlert } from '../ui'
import { PlusIcon, TrashIcon, SparklesIcon } from '../ui/icons'

interface QuestionItemProps {
  index: number
  question: string
  answer: string
  isAutoGenerated: boolean
  isGeneratingAnswer: boolean
  onUpdate: (index: number, field: 'question' | 'answer', value: string) => void
  onRemove: (index: number) => void
  onGenerateAnswer: (index: number) => void
}

const QuestionItem = memo(function QuestionItem({
  index,
  question,
  answer,
  isAutoGenerated,
  isGeneratingAnswer,
  onUpdate,
  onRemove,
  onGenerateAnswer,
}: QuestionItemProps) {
  return (
    <div className="bg-surface rounded-xl border border-border p-5 group">
      <div className="flex items-start justify-between gap-4 mb-3">
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <span className="flex-shrink-0 w-6 h-6 rounded-full bg-accent-subtle text-accent text-xs font-semibold flex items-center justify-center">
            {index + 1}
          </span>
          {isAutoGenerated && (
            <Badge variant="info" size="sm">自動</Badge>
          )}
        </div>
        <button
          onClick={() => onRemove(index)}
          className="opacity-0 group-hover:opacity-100 p-1.5 rounded-md hover:bg-error-subtle text-content-tertiary hover:text-error transition-all flex-shrink-0"
          title="削除"
        >
          <TrashIcon />
        </button>
      </div>

      <div className="space-y-3">
        <div>
          <label className="text-[10px] font-semibold text-content-secondary uppercase tracking-wider mb-1 block">
            質問
          </label>
          <textarea
            value={question}
            onChange={(e) => onUpdate(index, 'question', e.target.value)}
            className="w-full px-3 py-2 text-sm bg-surface-secondary border border-border rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent transition-colors"
            rows={2}
            placeholder="質問を入力..."
          />
        </div>
        <div>
          <div className="flex items-center justify-between mb-1">
            <label className="text-[10px] font-semibold text-content-secondary uppercase tracking-wider">
              回答
            </label>
            <button
              onClick={() => onGenerateAnswer(index)}
              disabled={isGeneratingAnswer || question.trim().length === 0}
              className="flex items-center gap-1 px-2 py-0.5 text-[10px] font-medium text-accent hover:bg-accent-subtle rounded transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              title="AIで回答を生成"
            >
              {isGeneratingAnswer ? (
                <Spinner size="sm" />
              ) : (
                <SparklesIcon className="w-3 h-3" />
              )}
              AI回答
            </button>
          </div>
          <textarea
            value={answer}
            onChange={(e) => onUpdate(index, 'answer', e.target.value)}
            className="w-full px-3 py-2 text-sm bg-surface-secondary border border-border rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent transition-colors"
            rows={4}
            placeholder="回答を入力..."
          />
        </div>
      </div>
    </div>
  )
})

export function QuestionsPage() {
  const {
    questions,
    isLoading,
    isSaving,
    hasUnsavedChanges,
    error,
    updateQuestion,
    addQuestion,
    removeQuestion,
    saveQuestions,
    generateQuestions,
    generateAnswer,
    isGenerating,
    generationProgress,
    generatingAnswerIndex,
  } = useInterviewQuestions()

  const handleUpdate = useCallback(
    (index: number, field: 'question' | 'answer', value: string) => {
      updateQuestion(index, field, value)
    },
    [updateQuestion],
  )

  const handleRemove = useCallback(
    (index: number) => {
      removeQuestion(index)
    },
    [removeQuestion],
  )

  const handleGenerate = useCallback(async () => {
    if (questions.length > 0) {
      const confirmed = window.confirm('既存の質問を上書きしますか？')
      if (!confirmed) return
    }
    await generateQuestions()
  }, [questions.length, generateQuestions])

  const handleGenerateAnswer = useCallback(
    (index: number) => {
      generateAnswer(index)
    },
    [generateAnswer],
  )

  return (
    <div className="h-full flex flex-col overflow-hidden">
      <PageHeader
        title="想定質問"
        subtitle="面接で聞かれそうな質問と回答を準備"
        action={
          <div className="flex items-center gap-2">
            <Badge variant="default" size="sm">
              {questions.length} / 20
            </Badge>
          </div>
        }
      />

      <div className="flex-1 overflow-y-auto p-6">
        {error && (
          <div className="mb-4">
            <ErrorAlert error={error} />
          </div>
        )}

        {/* アクションバー */}
        <div className="flex items-center gap-3 mb-6">
          <Button
            variant="primary"
            onClick={handleGenerate}
            leftIcon={<SparklesIcon />}
            isLoading={isGenerating}
            disabled={isGenerating}
          >
            {isGenerating ? `生成中... ${generationProgress.current} / ${generationProgress.total}` : 'AI自動生成'}
          </Button>
          <Button
            variant="secondary"
            onClick={addQuestion}
            leftIcon={<PlusIcon />}
            disabled={questions.length >= 20 || isGenerating}
          >
            手動で追加
          </Button>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-20">
            <Spinner size="lg" className="text-accent" />
          </div>
        ) : questions.length === 0 ? (
          <div className="text-center py-20">
            <svg className="w-12 h-12 text-content-tertiary mx-auto mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M8.625 12a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375M21 12c0 4.556-4.03 8.25-9 8.25a9.764 9.764 0 01-2.555-.337A5.972 5.972 0 015.41 20.97a5.969 5.969 0 01-.474-.065 4.48 4.48 0 00.978-2.025c.09-.457-.133-.901-.467-1.226C3.93 16.178 3 14.189 3 12c0-4.556 4.03-8.25 9-8.25s9 3.694 9 8.25z" />
            </svg>
            <p className="text-content-secondary text-sm">まだ想定質問がありません</p>
            <p className="text-content-tertiary text-xs mt-1">
              「AI自動生成」ボタンで履歴書から質問を自動生成、または「手動で追加」で質問を準備できます
            </p>
          </div>
        ) : (
          <div className="space-y-4 max-w-3xl">
            {questions.map((q, i) => (
              <QuestionItem
                key={(q as { localId?: string }).localId || q.id || `q-${i}`}
                index={i}
                question={q.question}
                answer={q.answer}
                isAutoGenerated={q.isAutoGenerated}
                isGeneratingAnswer={generatingAnswerIndex === i}
                onUpdate={handleUpdate}
                onRemove={handleRemove}
                onGenerateAnswer={handleGenerateAnswer}
              />
            ))}
          </div>
        )}
      </div>

      {/* 保存バー */}
      {hasUnsavedChanges && (
        <div className="px-6 py-3 border-t border-border bg-surface flex items-center justify-between">
          <span className="text-xs text-warning font-medium">未保存の変更があります</span>
          <Button variant="primary" onClick={saveQuestions} isLoading={isSaving}>
            保存
          </Button>
        </div>
      )}
    </div>
  )
}
