import { describe, it, expect, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'

const mockUseInterviewQuestions = vi.fn()

vi.mock('../../src/renderer/src/hooks/useInterviewQuestions', () => ({
  useInterviewQuestions: () => mockUseInterviewQuestions(),
  MAX_QUESTIONS: 20,
}))

import InterviewQuestionsPanel from '../../src/renderer/src/components/InterviewQuestionsPanel'

describe('InterviewQuestionsPanel', () => {
  const mockSaveQuestions = vi.fn().mockResolvedValue(undefined)
  const mockAddQuestion = vi.fn()
  const mockRemoveQuestion = vi.fn()
  const mockUpdateQuestion = vi.fn()

  const defaultHookReturn = {
    questions: [] as { localId: string; question: string; answer: string; isAutoGenerated: boolean }[],
    isLoading: false,
    isSaving: false,
    error: null as string | null,
    hasUnsavedChanges: false,
    updateQuestion: mockUpdateQuestion,
    addQuestion: mockAddQuestion,
    removeQuestion: mockRemoveQuestion,
    saveQuestions: mockSaveQuestions,
  }

  beforeEach(() => {
    vi.clearAllMocks()
    mockUseInterviewQuestions.mockReturnValue(defaultHookReturn)
  })

  it('should show loading spinner when loading', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, isLoading: true })
    render(<InterviewQuestionsPanel />)
    expect(screen.getByText('読み込み中...')).toBeDefined()
  })

  it('should render add question button', () => {
    render(<InterviewQuestionsPanel />)
    expect(screen.getByText('質問を追加')).toBeDefined()
  })

  it('should call addQuestion on add button click', () => {
    render(<InterviewQuestionsPanel />)
    fireEvent.click(screen.getByText('質問を追加'))
    expect(mockAddQuestion).toHaveBeenCalled()
  })

  it('should display questions when they exist', () => {
    const questions = [
      { localId: '1', question: '自己紹介をお願いします', answer: '回答テスト', isAutoGenerated: false },
      { localId: '2', question: '志望動機を教えてください', answer: '回答2', isAutoGenerated: true },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })

    render(<InterviewQuestionsPanel />)
    expect(screen.getByText('自己紹介をお願いします')).toBeDefined()
    expect(screen.getByText('志望動機を教えてください')).toBeDefined()
  })

  it('should show question count', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })

    render(<InterviewQuestionsPanel />)
    expect(screen.getByText(/1.*\/.*20/)).toBeDefined()
  })

  it('should show save button when there are unsaved changes', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, hasUnsavedChanges: true })
    render(<InterviewQuestionsPanel />)
    expect(screen.getByText('保存')).toBeDefined()
  })

  it('should not show save button when no unsaved changes', () => {
    render(<InterviewQuestionsPanel />)
    expect(screen.queryByText('保存')).toBeNull()
  })

  it('should call saveQuestions on save click', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, hasUnsavedChanges: true })
    render(<InterviewQuestionsPanel />)
    fireEvent.click(screen.getByText('保存'))
    expect(mockSaveQuestions).toHaveBeenCalled()
  })

  it('should show error when error exists', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, error: 'エラー発生' })
    render(<InterviewQuestionsPanel />)
    expect(screen.getByText(/エラー/)).toBeDefined()
  })

  it('should show auto-generated badge for auto-generated questions', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: true },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })

    render(<InterviewQuestionsPanel />)
    expect(screen.getByText('自動')).toBeDefined()
  })

  it('should show empty state when no questions', () => {
    render(<InterviewQuestionsPanel />)
    expect(screen.getByText('想定質問を追加してください')).toBeDefined()
  })
})
