import { describe, it, expect, vi } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'

const mockUseInterviewQuestions = vi.fn()

vi.mock('../../src/renderer/src/hooks/useInterviewQuestions', () => ({
  useInterviewQuestions: () => mockUseInterviewQuestions(),
}))

vi.mock('../../src/renderer/src/components/ui/PageHeader', () => ({
  PageHeader: ({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) => (
    <div data-testid="page-header">
      <h1>{title}</h1>
      {subtitle && <p>{subtitle}</p>}
      {action && <div data-testid="page-header-action">{action}</div>}
    </div>
  ),
}))

vi.mock('../../src/renderer/src/components/ui', () => ({
  Button: ({ children, onClick, isLoading, disabled, leftIcon, ...rest }: { children: React.ReactNode; onClick?: () => void; isLoading?: boolean; disabled?: boolean; leftIcon?: React.ReactNode; variant?: string; size?: string }) => (
    <button onClick={onClick} disabled={isLoading || disabled}>{isLoading ? 'Loading...' : children}</button>
  ),
  Badge: ({ children }: { children: React.ReactNode }) => <span data-testid="badge">{children}</span>,
  Spinner: ({ size }: { size?: string }) => <div data-testid="spinner">Loading</div>,
  ErrorAlert: ({ error }: { error: string }) => <div data-testid="error-alert">{error}</div>,
}))

vi.mock('../../src/renderer/src/components/ui/icons', () => ({
  PlusIcon: () => <span>plus</span>,
  TrashIcon: () => <span>trash</span>,
  SparklesIcon: () => <span>sparkles</span>,
}))

import { QuestionsPage } from '../../src/renderer/src/components/pages/QuestionsPage'

describe('QuestionsPage', () => {
  const mockSaveQuestions = vi.fn()
  const mockAddQuestion = vi.fn()
  const mockRemoveQuestion = vi.fn()
  const mockUpdateQuestion = vi.fn()

  const defaultHookReturn = {
    questions: [] as { localId?: string; id?: string; question: string; answer: string; isAutoGenerated: boolean }[],
    isLoading: false,
    isSaving: false,
    hasUnsavedChanges: false,
    error: null as string | null,
    updateQuestion: mockUpdateQuestion,
    addQuestion: mockAddQuestion,
    removeQuestion: mockRemoveQuestion,
    saveQuestions: mockSaveQuestions,
  }

  beforeEach(() => {
    vi.clearAllMocks()
    mockUseInterviewQuestions.mockReturnValue(defaultHookReturn)
  })

  it('should render the page header with correct title', () => {
    render(<QuestionsPage />)
    expect(screen.getByText('想定質問')).toBeDefined()
  })

  it('should render the page header with correct subtitle', () => {
    render(<QuestionsPage />)
    expect(screen.getByText('面接で聞かれそうな質問と回答を準備')).toBeDefined()
  })

  it('should show question count badge in header action', () => {
    render(<QuestionsPage />)
    expect(screen.getByText('0 / 20')).toBeDefined()
  })

  it('should show correct question count when questions exist', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
      { localId: '2', question: 'Q2', answer: 'A2', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    expect(screen.getByText('2 / 20')).toBeDefined()
  })

  it('should render manual add button', () => {
    render(<QuestionsPage />)
    expect(screen.getByText('手動で追加')).toBeDefined()
  })

  it('should call addQuestion on manual add click', () => {
    render(<QuestionsPage />)
    fireEvent.click(screen.getByText('手動で追加'))
    expect(mockAddQuestion).toHaveBeenCalled()
  })

  it('should show spinner when loading', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, isLoading: true })
    render(<QuestionsPage />)
    expect(screen.getByTestId('spinner')).toBeDefined()
  })

  it('should show empty state when no questions and not loading', () => {
    render(<QuestionsPage />)
    expect(screen.getByText('まだ想定質問がありません')).toBeDefined()
  })

  it('should show empty state hint text', () => {
    render(<QuestionsPage />)
    expect(screen.getByText(/「手動で追加」で質問を準備できます/)).toBeDefined()
  })

  it('should display questions when they exist', () => {
    const questions = [
      { localId: '1', question: '自己紹介をお願いします', answer: '回答テスト', isAutoGenerated: false },
      { localId: '2', question: '志望動機を教えてください', answer: '回答2', isAutoGenerated: true },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    // Questions are rendered via textareas with values
    const textareas = screen.getAllByRole('textbox')
    expect(textareas.length).toBeGreaterThanOrEqual(4) // 2 questions * 2 fields each
  })

  it('should show question number labels', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    expect(screen.getByText('1')).toBeDefined()
  })

  it('should show auto-generated badge for auto-generated questions', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: true },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    // Badge renders with text "自動"
    expect(screen.getByText('自動')).toBeDefined()
  })

  it('should not show auto-generated badge for manual questions', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    expect(screen.queryByText('自動')).toBeNull()
  })

  it('should show save bar when there are unsaved changes', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, hasUnsavedChanges: true })
    render(<QuestionsPage />)
    expect(screen.getByText('未保存の変更があります')).toBeDefined()
    expect(screen.getByText('保存')).toBeDefined()
  })

  it('should not show save bar when no unsaved changes', () => {
    render(<QuestionsPage />)
    expect(screen.queryByText('未保存の変更があります')).toBeNull()
    expect(screen.queryByText('保存')).toBeNull()
  })

  it('should call saveQuestions on save button click', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, hasUnsavedChanges: true })
    render(<QuestionsPage />)
    fireEvent.click(screen.getByText('保存'))
    expect(mockSaveQuestions).toHaveBeenCalled()
  })

  it('should show error alert when error exists', () => {
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, error: 'エラーが発生しました' })
    render(<QuestionsPage />)
    expect(screen.getByTestId('error-alert')).toBeDefined()
    expect(screen.getByText('エラーが発生しました')).toBeDefined()
  })

  it('should not show error alert when no error', () => {
    render(<QuestionsPage />)
    expect(screen.queryByTestId('error-alert')).toBeNull()
  })

  it('should render question and answer labels', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    expect(screen.getByText('質問')).toBeDefined()
    expect(screen.getByText('回答')).toBeDefined()
  })

  it('should render delete button for each question', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    expect(screen.getByTitle('削除')).toBeDefined()
  })

  it('should call removeQuestion when delete button is clicked', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    fireEvent.click(screen.getByTitle('削除'))
    expect(mockRemoveQuestion).toHaveBeenCalledWith(0)
  })

  it('should call updateQuestion when question textarea is changed', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    const textareas = screen.getAllByRole('textbox')
    // First textarea is the question field
    fireEvent.change(textareas[0], { target: { value: '新しい質問' } })
    expect(mockUpdateQuestion).toHaveBeenCalledWith(0, 'question', '新しい質問')
  })

  it('should call updateQuestion when answer textarea is changed', () => {
    const questions = [
      { localId: '1', question: 'Q1', answer: 'A1', isAutoGenerated: false },
    ]
    mockUseInterviewQuestions.mockReturnValue({ ...defaultHookReturn, questions })
    render(<QuestionsPage />)
    const textareas = screen.getAllByRole('textbox')
    // Second textarea is the answer field
    fireEvent.change(textareas[1], { target: { value: '新しい回答' } })
    expect(mockUpdateQuestion).toHaveBeenCalledWith(0, 'answer', '新しい回答')
  })
})
