import { describe, it, expect, vi, beforeEach } from 'vitest'

const { mockAuthenticatedFetch } = vi.hoisted(() => ({
  mockAuthenticatedFetch: vi.fn(),
}))

vi.mock('../../src/services/auth.service', () => ({
  authService: {
    authenticatedFetch: mockAuthenticatedFetch,
  },
}))

vi.mock('../../src/services/logger.service', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}))

import { questionsService } from '../../src/services/questions.service'

function makeResponse(body: unknown, status = 200): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    json: () => Promise.resolve(body),
  } as Response
}

const sampleQuestion = {
  id: 'q-1',
  question: '自己紹介をお願いします',
  answer: '私は田中と申します',
  isAutoGenerated: false,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
}

describe('questionsService', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  describe('getQuestions', () => {
    it('should return list of questions', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: true, questions: [sampleQuestion] })
      )

      const questions = await questionsService.getQuestions()
      expect(questions).toHaveLength(1)
      expect(questions[0].id).toBe('q-1')
      expect(questions[0].question).toBe('自己紹介をお願いします')
      expect(mockAuthenticatedFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/questions'),
        expect.objectContaining({ method: 'GET' })
      )
    })

    it('should return empty array on 401 unauthorized', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({ error: 'Unauthorized' }, 401))

      const questions = await questionsService.getQuestions()
      expect(questions).toEqual([])
    })

    it('should return empty array on network error', async () => {
      mockAuthenticatedFetch.mockRejectedValue(new Error('Network error'))

      const questions = await questionsService.getQuestions()
      expect(questions).toEqual([])
    })

    it('should return empty array on 500 error', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({}, 500))

      const questions = await questionsService.getQuestions()
      expect(questions).toEqual([])
    })

    it('should return empty array when success is false', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: false, error: 'DB error' })
      )

      const questions = await questionsService.getQuestions()
      expect(questions).toEqual([])
    })

    it('should return empty array when questions field is missing', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: true })
      )

      const questions = await questionsService.getQuestions()
      expect(questions).toEqual([])
    })
  })

  describe('saveQuestions', () => {
    const questionInputs = [{ question: '自己紹介', answer: 'はい' }]

    it('should save questions and return saved list', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: true, questions: [sampleQuestion] })
      )

      const saved = await questionsService.saveQuestions(questionInputs)
      expect(saved).toHaveLength(1)
      expect(saved[0].id).toBe('q-1')
      expect(mockAuthenticatedFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/questions'),
        expect.objectContaining({ method: 'POST' })
      )
    })

    it('should throw error when response is not ok', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ error: 'Validation error' }, 400)
      )

      await expect(questionsService.saveQuestions(questionInputs)).rejects.toThrow(
        'Validation error'
      )
    })

    it('should throw generic error when no error detail on 500', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({}, 500))

      await expect(questionsService.saveQuestions(questionInputs)).rejects.toThrow(
        'Save failed: 500'
      )
    })

    it('should throw error when success is false', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: false, error: 'Conflict' })
      )

      await expect(questionsService.saveQuestions(questionInputs)).rejects.toThrow('Conflict')
    })

    it('should return empty array when questions field is missing on success', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({ success: true }))

      const saved = await questionsService.saveQuestions(questionInputs)
      expect(saved).toEqual([])
    })
  })

  describe('deleteQuestion', () => {
    it('should delete question successfully', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({ success: true }))

      await expect(questionsService.deleteQuestion('q-1')).resolves.toBeUndefined()
      expect(mockAuthenticatedFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/questions/q-1'),
        expect.objectContaining({ method: 'DELETE' })
      )
    })

    it('should throw error when response is not ok', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ error: 'Question not found' }, 404)
      )

      await expect(questionsService.deleteQuestion('q-999')).rejects.toThrow('Question not found')
    })

    it('should throw generic error when no error detail on 500', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({}, 500))

      await expect(questionsService.deleteQuestion('q-999')).rejects.toThrow('Delete failed: 500')
    })
  })

  describe('generateQuestions', () => {
    const generatedQuestion = {
      question: 'Reactの経験を教えてください',
      suggestedAnswer: '3年間Reactを使用して...',
      category: 'technical',
    }

    it('should generate questions and return list', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: true, questions: [generatedQuestion], tokensUsed: 1500 })
      )

      const generated = await questionsService.generateQuestions(5)
      expect(generated).toHaveLength(1)
      expect(generated[0].question).toBe('Reactの経験を教えてください')
      expect(mockAuthenticatedFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/questions/generate'),
        expect.objectContaining({ method: 'POST' })
      )
    })

    it('should use default count of 10 when not specified', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: true, questions: [] })
      )

      await questionsService.generateQuestions()

      const callBody = JSON.parse(
        (mockAuthenticatedFetch.mock.calls[0][1] as RequestInit).body as string
      )
      expect(callBody.count).toBe(10)
    })

    it('should throw error when response is not ok', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ error: 'Documents not found' }, 404)
      )

      await expect(questionsService.generateQuestions()).rejects.toThrow('Documents not found')
    })

    it('should throw generic error when no error detail on 500', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({}, 500))

      await expect(questionsService.generateQuestions()).rejects.toThrow('Generation failed: 500')
    })

    it('should throw error when success is false', async () => {
      mockAuthenticatedFetch.mockResolvedValue(
        makeResponse({ success: false, error: 'Usage limit exceeded' })
      )

      await expect(questionsService.generateQuestions()).rejects.toThrow('Usage limit exceeded')
    })

    it('should return empty array when questions field is missing on success', async () => {
      mockAuthenticatedFetch.mockResolvedValue(makeResponse({ success: true }))

      const generated = await questionsService.generateQuestions()
      expect(generated).toEqual([])
    })
  })
})
