import { describe, it, expect, vi, beforeEach } from 'vitest'
import { renderHook, act, waitFor } from '@testing-library/react'

// Mock renderer logger
vi.mock('../../src/renderer/src/utils/logger', () => ({
  createLogger: () => ({
    debug: vi.fn(),
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}))

import { useInterviewQuestions, MAX_QUESTIONS } from '../../src/renderer/src/hooks/useInterviewQuestions'

const mockQuestions = window.electron.questions

describe('useInterviewQuestions', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // Default: list returns empty
    ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
      success: true,
      questions: [],
    })
    // Mock crypto.randomUUID
    vi.stubGlobal('crypto', {
      randomUUID: vi.fn().mockReturnValue('mock-uuid-1234'),
    })
  })

  describe('initial state', () => {
    it('should return initial loading state', () => {
      const { result } = renderHook(() => useInterviewQuestions())

      // isLoading is true initially while loadQuestions runs
      expect(result.current.isLoading).toBe(true)
      expect(result.current.isSaving).toBe(false)
      expect(result.current.isGenerating).toBe(false)
      expect(result.current.error).toBeNull()
      // hasUnsavedChanges = JSON.stringify([]) !== '' (initially '') → true
      // after load completes it settles to false, but initially it may be true
      expect(typeof result.current.hasUnsavedChanges).toBe('boolean')
    })

    it('should load questions on mount', async () => {
      const serverQuestions = [
        {
          id: 'q1',
          question: '自己紹介をしてください',
          answer: 'エンジニアの太郎です',
          sortOrder: 0,
          isAutoGenerated: false,
          createdAt: '2026-01-01',
          updatedAt: '2026-01-01',
        },
      ]
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: serverQuestions,
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.questions).toHaveLength(1)
      expect(result.current.questions[0].question).toBe('自己紹介をしてください')
      expect(result.current.questions[0].answer).toBe('エンジニアの太郎です')
      expect(result.current.questions[0].id).toBe('q1')
      expect(result.current.questions[0].localId).toBe('q1')
      expect(result.current.hasUnsavedChanges).toBe(false)
    })

    it('should finish loading with empty questions', async () => {
      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.questions).toEqual([])
    })

    it('should set error when loading fails', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: false,
        error: 'Network error',
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.error).toBe('Network error')
      expect(result.current.questions).toEqual([])
    })

    it('should set error when loading throws', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockRejectedValue(
        new Error('Connection refused')
      )

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.error).toBe('Error: Connection refused')
    })
  })

  describe('addQuestion', () => {
    it('should add a new empty question', async () => {
      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.addQuestion()
      })

      expect(result.current.questions).toHaveLength(1)
      expect(result.current.questions[0].question).toBe('')
      expect(result.current.questions[0].answer).toBe('')
      expect(result.current.questions[0].isAutoGenerated).toBe(false)
      expect(result.current.questions[0].localId).toBe('mock-uuid-1234')
    })

    it('should not exceed MAX_QUESTIONS', async () => {
      // Start with MAX_QUESTIONS items
      const manyQuestions = Array.from({ length: MAX_QUESTIONS }, (_, i) => ({
        id: `q${i}`,
        question: `Question ${i}`,
        answer: `Answer ${i}`,
        sortOrder: i,
        isAutoGenerated: false,
        createdAt: '2026-01-01',
        updatedAt: '2026-01-01',
      }))
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: manyQuestions,
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.questions).toHaveLength(MAX_QUESTIONS)

      act(() => {
        result.current.addQuestion()
      })

      // Should still be MAX_QUESTIONS
      expect(result.current.questions).toHaveLength(MAX_QUESTIONS)
    })

    it('should mark hasUnsavedChanges after adding', async () => {
      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.hasUnsavedChanges).toBe(false)

      act(() => {
        result.current.addQuestion()
      })

      expect(result.current.hasUnsavedChanges).toBe(true)
    })
  })

  describe('updateQuestion', () => {
    it('should update question text at given index', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          {
            id: 'q1',
            question: 'Old question',
            answer: 'Old answer',
            sortOrder: 0,
            isAutoGenerated: false,
            createdAt: '2026-01-01',
            updatedAt: '2026-01-01',
          },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'New question')
      })

      expect(result.current.questions[0].question).toBe('New question')
      expect(result.current.questions[0].answer).toBe('Old answer')
      expect(result.current.hasUnsavedChanges).toBe(true)
    })

    it('should update answer text at given index', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          {
            id: 'q1',
            question: 'Question',
            answer: 'Old answer',
            sortOrder: 0,
            isAutoGenerated: false,
            createdAt: '2026-01-01',
            updatedAt: '2026-01-01',
          },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.updateQuestion(0, 'answer', 'New answer')
      })

      expect(result.current.questions[0].answer).toBe('New answer')
      expect(result.current.questions[0].question).toBe('Question')
    })

    it('should not affect other questions', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          { id: 'q1', question: 'Q1', answer: 'A1', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
          { id: 'q2', question: 'Q2', answer: 'A2', sortOrder: 1, isAutoGenerated: false, createdAt: '', updatedAt: '' },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Updated Q1')
      })

      expect(result.current.questions[0].question).toBe('Updated Q1')
      expect(result.current.questions[1].question).toBe('Q2')
      expect(result.current.questions[1].answer).toBe('A2')
    })
  })

  describe('removeQuestion', () => {
    it('should remove question at given index', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          { id: 'q1', question: 'Q1', answer: 'A1', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
          { id: 'q2', question: 'Q2', answer: 'A2', sortOrder: 1, isAutoGenerated: false, createdAt: '', updatedAt: '' },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.removeQuestion(0)
      })

      expect(result.current.questions).toHaveLength(1)
      expect(result.current.questions[0].question).toBe('Q2')
    })

    it('should mark hasUnsavedChanges after removing', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          { id: 'q1', question: 'Q1', answer: 'A1', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.removeQuestion(0)
      })

      expect(result.current.hasUnsavedChanges).toBe(true)
    })
  })

  describe('saveQuestions', () => {
    it('should save questions and update state', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [],
      })

      const savedResponse = [
        {
          id: 'saved-1',
          question: 'Saved question',
          answer: 'Saved answer',
          sortOrder: 0,
          isAutoGenerated: false,
          createdAt: '2026-01-01',
          updatedAt: '2026-01-01',
        },
      ]
      ;(mockQuestions.save as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: savedResponse,
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      // Add a question first
      act(() => {
        result.current.addQuestion()
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Saved question')
        result.current.updateQuestion(0, 'answer', 'Saved answer')
      })

      await act(async () => {
        await result.current.saveQuestions()
      })

      expect(mockQuestions.save).toHaveBeenCalled()
      expect(result.current.isSaving).toBe(false)
      expect(result.current.questions[0].id).toBe('saved-1')
      expect(result.current.hasUnsavedChanges).toBe(false)
    })

    it('should filter out questions with empty question text', async () => {
      ;(mockQuestions.save as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      // Add two questions, one empty
      act(() => {
        result.current.addQuestion()
        result.current.addQuestion()
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Valid question')
        result.current.updateQuestion(0, 'answer', 'Valid answer')
        // Leave second question empty
      })

      await act(async () => {
        await result.current.saveQuestions()
      })

      const savedArgs = (mockQuestions.save as ReturnType<typeof vi.fn>).mock.calls[0][0]
      expect(savedArgs).toHaveLength(1)
      expect(savedArgs[0].question).toBe('Valid question')
    })

    it('should set error on save failure', async () => {
      ;(mockQuestions.save as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: false,
        error: 'Save failed',
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.addQuestion()
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Test')
      })

      await act(async () => {
        await result.current.saveQuestions()
      })

      expect(result.current.error).toBe('Save failed')
      expect(result.current.isSaving).toBe(false)
    })

    it('should handle save exception', async () => {
      ;(mockQuestions.save as ReturnType<typeof vi.fn>).mockRejectedValue(
        new Error('Network error')
      )

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.addQuestion()
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Test')
      })

      await act(async () => {
        await result.current.saveQuestions()
      })

      expect(result.current.error).toBe('Error: Network error')
      expect(result.current.isSaving).toBe(false)
    })
  })

  describe('refreshQuestions', () => {
    it('should reload questions from server', async () => {
      let callCount = 0
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockImplementation(() => {
        callCount++
        if (callCount === 1) {
          return Promise.resolve({ success: true, questions: [] })
        }
        return Promise.resolve({
          success: true,
          questions: [
            { id: 'new-q', question: 'Refreshed', answer: 'Answer', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
          ],
        })
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.questions).toHaveLength(0)

      await act(async () => {
        await result.current.refreshQuestions()
      })

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.questions).toHaveLength(1)
      expect(result.current.questions[0].question).toBe('Refreshed')
    })
  })

  describe('hasUnsavedChanges', () => {
    it('should be false after loading', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          { id: 'q1', question: 'Q', answer: 'A', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      expect(result.current.hasUnsavedChanges).toBe(false)
    })

    it('should be true after modifying', async () => {
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          { id: 'q1', question: 'Q', answer: 'A', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
        ],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Modified')
      })

      expect(result.current.hasUnsavedChanges).toBe(true)
    })

    it('should be false after saving', async () => {
      const savedQuestion = {
        id: 'q1',
        question: 'Modified',
        answer: 'A',
        sortOrder: 0,
        isAutoGenerated: false,
        createdAt: '',
        updatedAt: '',
      }
      ;(mockQuestions.list as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [
          { id: 'q1', question: 'Q', answer: 'A', sortOrder: 0, isAutoGenerated: false, createdAt: '', updatedAt: '' },
        ],
      })
      ;(mockQuestions.save as ReturnType<typeof vi.fn>).mockResolvedValue({
        success: true,
        questions: [savedQuestion],
      })

      const { result } = renderHook(() => useInterviewQuestions())

      await waitFor(() => {
        expect(result.current.isLoading).toBe(false)
      })

      act(() => {
        result.current.updateQuestion(0, 'question', 'Modified')
      })

      expect(result.current.hasUnsavedChanges).toBe(true)

      await act(async () => {
        await result.current.saveQuestions()
      })

      expect(result.current.hasUnsavedChanges).toBe(false)
    })
  })
})
